{% set version = "6.5.0.dev0" %}
{% set variant = "openblas" %}
{% set commit_id = "10439e226f125ae5411a65c6d944d3f2c9d6f070" %}


package:
  name: ncl
  version: {{ version }}

source:
  git_url: https://github.com/NCAR/ncl.git
  git_rev: {{ commit_id }}
  patches:
    - grib2.patch


build:
  number: 0
  skip: True  # [win]
  features:
    - blas_{{ variant }}  # [not win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*  # [linux]
    - curl >=7.44.0,<8
    - freetype 2.8.1  # [linux]
    - gsl  2.2.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.2.*
    - libiconv 1.15
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - pixman 0.34.*  # [linux]
    - proj4 4.9.3
    - udunits2
    - zlib 1.2.11
    - flex
    - gcc
    - pkg-config
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*  # [linux]
    - curl >=7.44.0,<8
    - freetype 2.8.1  # [linux]
    - gsl  2.2.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.2.*
    - libiconv 1.15
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - pixman 0.34.*  # [linux]
    - proj4 4.9.3
    - udunits2
    - zlib 1.2.11
    - esmf
    - libgcc
    - xorg-imake  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-makedepend  # [linux]

test:
  source_files:
    - install/make-tarfile/check_files
  commands:
    - test "$(ncl -V)" = "{{ version }}+{{ GIT_FULL_HASH[0:7] }}"
    - NCARG_ROOT=${PREFIX} install/make-tarfile/check_files | grep -qv '^<'
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://ncl.ucar.edu/
  license: 'NCL Source Code'
  license_file: COPYING
  summary: 'NCAR Command Language'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
