travis:
  secure:
    BINSTAR_TOKEN: HPYkyCzggaAysvZZeS215NMzRR+tz8sEuKz9PY6rnm6l7/Gku11VRz/fFm7DcFtjpce16EwKfHA1etLp4VND0lN1WO32IcwugYK+RRFuE2g3NP2oJWTHKqE+1i8GimTc6zM62CM/f2iOEYsih6c4fN8rQxwBLufV3x6/4xsj1Q5BxUkmDWLcEEgS0xLRHvw2+P8bejQZbaQtL92Z+s2ii06zxz/oF2+PIM4836iPgQOzg2WmvxfTcLrjvrHaMNVmjq8KoaF/FS1eMiR9jkK1HLBUoUQzdtaXqkt6/tqUgXv64d2QsCltBkc18w9RB8do586GMdxw2vi5fcDB/POtIkBTZ8AMvKViQcQEM40vdT1Qdcmp82ZMG7rCweettLa76FLFSEsKSOSMn1ASyiGrYlJCbn5wz9CkChkzV81sF+8JmRCSd9wKACRJERl1Zukz5YI+vOMs7xUHjFBVua8W1RcNw1JNQNJl1pUPki/ryZiqhXzT+p/LMbu7BqN8XC71P47BI0QvTASEpBeiglU8cgTuZeRGpi0d2NPf0AIhWcY7NIY01MzG7AIWYimLPjz5y5YiqT7wYPfI216MTYpLDyhJOP038HsccP7wYjibVSEm4nmLKaxsIZIFnwi3FZQisrq4g3sWie7ykQF6Tcpe/K/rxRlARUuPRlzyL1WQcZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle
