travis:
  secure:
    BINSTAR_TOKEN: IOkMcOSV0qNzlK2msnRBFNq2mP+wbTzyugoA/D24RSxBTc7A6QSec2YWS58tkJDhpaKMXsN0HoSsu/k0IouQ73tbU+7ARsQvi5klxZkTIJbEfcON9OjmgUV7zOYMffd/JBSlQGLRsG0VPBwLtg5B9IrnhjhWnaa6FiJZYRSAJBaQKT5em7fj1DYN/n1l2IZr6UNqEdOuXXdgNtg2QlplSwTC4O6xSdyIJWncZJoHYqktUidbgz/WgSQL3KZwibqCvoWenywO7+KGGINvVbr8/ljTdQUqyaHDqAKbxVk7UGASmf/VS0JJloFaqnhGAs+C2ezLANZjMyAV1MQ/GVM1yEZD+QA6rLdLxm8uBWIFmzYE4epVQiWWuIwV12bG+IC6UaMfkfz7hprsEmMMCU5QVdL/R4oEIcNJRUqbusp1T+AUB9/0loET3xI06FLPNjL7vaeJCcxpqTvvKLtgnG6pD0Y3u6eS7BGeqoDuJFv+RGWkJjnMpgeGFFC3ONMSu4c15YcYZeEuPZQNaSr8jJYgBfyc0Z0R89OPzuiuS8C13pJxrkeLJt0Kym4WP4ij/oyeR81/7G9ZAj87p6hBgJPjCEI86WCmz6EjTotetzmS+0Uy2uuSUKC3yGEcF937L6RNJIc885DHFjqjRVR89Gv4r5eZ2kdj/nTC2uVpM+dv9OQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
